# Generated by Django 5.0.6 on 2024-05-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.IntegerField()),
                ("category", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField(verbose_name="Date")),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.IntegerField()),
                ("source", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField(verbose_name="Date")),
            ],
        ),
    ]
